/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;


import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abner
 */
public class Factura extends javax.swing.JFrame {

     public static DefaultTableModel modelof;
     int filas;
     
     
    public Factura() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/Praia.png")).getImage());
        this.setLocationRelativeTo(this);
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setMoverVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this, false);
        
        modelof = new DefaultTableModel();
        
        modelof.addColumn("No. DOC");
        modelof.addColumn("EMISOR");
        modelof.addColumn("NIT");
        modelof.addColumn("CLIENTE");
        modelof.addColumn("DIRECCION");
        modelof.addColumn("DESCRIPCION");
        modelof.addColumn("ATENDIO");
        modelof.addColumn("FECHA EMSION");
        modelof.addColumn("SUBTOTAL");
        modelof.addColumn("IVA");
        modelof.addColumn("TOTAL");
        
        tb_factura.setModel(modelof);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_fondo = new javax.swing.JPanel();
        pn_encabezado = new javax.swing.JPanel();
        bt_cerra = new javax.swing.JButton();
        lb_encabezado = new javax.swing.JLabel();
        pn_menu = new javax.swing.JPanel();
        bt_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_factura = new javax.swing.JTable();
        cb_clienteFac = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_emisor = new javax.swing.JTextArea();
        cb_recepcionista = new javax.swing.JComboBox<>();
        txt_emision = new RSMaterialComponent.RSTextFieldIconUno();
        txt_no_fac = new RSMaterialComponent.RSTextFieldIconUno();
        cb_NITFAC = new javax.swing.JComboBox<>();
        txt_direccion = new RSMaterialComponent.RSTextFieldIconUno();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Praia | Factura");
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        setUndecorated(true);

        pn_fondo.setBackground(new java.awt.Color(255, 255, 255));

        pn_encabezado.setBackground(new java.awt.Color(255, 204, 0));

        bt_cerra.setBackground(new java.awt.Color(255, 204, 0));
        bt_cerra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        bt_cerra.setToolTipText("Cerrar.. que esperabas?");
        bt_cerra.setBorder(null);
        bt_cerra.setContentAreaFilled(false);
        bt_cerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerraActionPerformed(evt);
            }
        });

        lb_encabezado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lb_encabezado.setForeground(new java.awt.Color(0, 102, 102));
        lb_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        lb_encabezado.setText("Facturacion");

        pn_menu.setBackground(new java.awt.Color(255, 255, 102));

        bt_imprimir.setBackground(new java.awt.Color(255, 204, 0));
        bt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf.png"))); // NOI18N
        bt_imprimir.setToolTipText("Imprimir Factura");
        bt_imprimir.setBorder(null);
        bt_imprimir.setContentAreaFilled(false);
        bt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_encabezadoLayout = new javax.swing.GroupLayout(pn_encabezado);
        pn_encabezado.setLayout(pn_encabezadoLayout);
        pn_encabezadoLayout.setHorizontalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lb_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_cerra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pn_encabezadoLayout.setVerticalGroup(
            pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_encabezado)
                    .addComponent(bt_cerra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tb_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_factura);

        cb_clienteFac.setBackground(new java.awt.Color(255, 255, 255));
        cb_clienteFac.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cb_clienteFac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Cliente...", " " }));

        ta_emisor.setColumns(20);
        ta_emisor.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ta_emisor.setRows(5);
        ta_emisor.setText("\t\t\t\tPraia Hotels & Resorts GmBh.\n\t\t\tFlughafen Tegel, 13405 Berlin, Deutchland.\n\t\t   ----------------------------------------------------\n\t\t\t\t\tHOTEL PRAIA\n\t\t          PLAYA PRIVADA DE ALGUN LUGAR, GUATEMALA\n                ----------------------------------------------------------------\n\t                      Documento tributario electronico \n\t\t\t\t\t   \n\t\t\t\t\t -FACTURA-\n\t\t\t\t             \n\t\t\t\t  Autorizacion M15c0j0n3s\n\t\t\t   SERIE: AM2\t\tNIT: 12345678-F");
        jScrollPane2.setViewportView(ta_emisor);

        cb_recepcionista.setBackground(new java.awt.Color(255, 255, 255));
        cb_recepcionista.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cb_recepcionista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quien atendio...", "Paco del Monte", "Elsa Patito", "Rosamel Anastacia", "Aitor Tilla", " " }));

        txt_emision.setForeground(new java.awt.Color(0, 102, 102));
        txt_emision.setToolTipText("Ingresa fecha de factura");
        txt_emision.setAutoscrolls(false);
        txt_emision.setBorderColor(new java.awt.Color(255, 204, 0));
        txt_emision.setColorIcon(new java.awt.Color(255, 204, 0));
        txt_emision.setColorTransparente(true);
        txt_emision.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_emision.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DATE_RANGE);
        txt_emision.setPlaceholder("Fecha de emision");
        txt_emision.setSelectionColor(new java.awt.Color(0, 102, 102));
        txt_emision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emisionActionPerformed(evt);
            }
        });
        txt_emision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emisionKeyTyped(evt);
            }
        });

        txt_no_fac.setForeground(new java.awt.Color(0, 102, 102));
        txt_no_fac.setToolTipText("Ingresa numero de factura");
        txt_no_fac.setAutoscrolls(false);
        txt_no_fac.setBorderColor(new java.awt.Color(255, 204, 0));
        txt_no_fac.setColorIcon(new java.awt.Color(255, 204, 0));
        txt_no_fac.setColorTransparente(true);
        txt_no_fac.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_no_fac.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        txt_no_fac.setInheritsPopupMenu(true);
        txt_no_fac.setPlaceholder("Numero de factura");
        txt_no_fac.setSelectionColor(new java.awt.Color(0, 102, 102));
        txt_no_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_facActionPerformed(evt);
            }
        });
        txt_no_fac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_no_facKeyTyped(evt);
            }
        });

        cb_NITFAC.setBackground(new java.awt.Color(255, 255, 255));
        cb_NITFAC.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cb_NITFAC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar NIT...", "CF", " " }));

        txt_direccion.setForeground(new java.awt.Color(0, 102, 102));
        txt_direccion.setToolTipText("Ingresa direccion del cliente");
        txt_direccion.setAutoscrolls(false);
        txt_direccion.setBorderColor(new java.awt.Color(255, 204, 0));
        txt_direccion.setColorIcon(new java.awt.Color(255, 204, 0));
        txt_direccion.setColorTransparente(true);
        txt_direccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_direccion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCATION_CITY);
        txt_direccion.setPlaceholder("Direccion");
        txt_direccion.setSelectionColor(new java.awt.Color(0, 102, 102));
        txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionActionPerformed(evt);
            }
        });
        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pn_fondoLayout = new javax.swing.GroupLayout(pn_fondo);
        pn_fondo.setLayout(pn_fondoLayout);
        pn_fondoLayout.setHorizontalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(pn_fondoLayout.createSequentialGroup()
                        .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pn_fondoLayout.createSequentialGroup()
                                .addComponent(txt_no_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_emision, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_fondoLayout.createSequentialGroup()
                                .addComponent(cb_clienteFac, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(cb_NITFAC, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_recepcionista, 0, 242, Short.MAX_VALUE)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pn_fondoLayout.setVerticalGroup(
            pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_fondoLayout.createSequentialGroup()
                .addComponent(pn_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_emision, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_no_fac, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cb_recepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_NITFAC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_clienteFac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void CrearInterfazProv(){
          
        this.tb_factura.setModel(modelof);
        this.modelof.addColumn("No. DOC");
        this.modelof.addColumn("EMISOR");
        this.modelof.addColumn("NIT");
        this.modelof.addColumn("CLIENTE");
        this.modelof.addColumn("DIRECCION");
        this.modelof.addColumn("DESCRIPCION");
        this.modelof.addColumn("ATENDIO");
        this.modelof.addColumn("FECHA EMSION");
        this.modelof.addColumn("SUBTOTAL");
        this.modelof.addColumn("IVA");
        this.modelof.addColumn("TOTAL");
        
    }
     
    private void bt_cerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerraActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_cerraActionPerformed

    private void txt_emisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emisionActionPerformed

    private void txt_emisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emisionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emisionKeyTyped

    private void txt_no_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_facActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_facActionPerformed

    private void txt_no_facKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_no_facKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_facKeyTyped

    private void txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionActionPerformed

    private void txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionKeyTyped

    private void bt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirActionPerformed
       
           // TODO add your handling code here:
    }//GEN-LAST:event_bt_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cerra;
    private javax.swing.JButton bt_imprimir;
    private javax.swing.JComboBox<String> cb_NITFAC;
    private javax.swing.JComboBox<String> cb_clienteFac;
    private javax.swing.JComboBox<String> cb_recepcionista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_encabezado;
    private javax.swing.JPanel pn_encabezado;
    private javax.swing.JPanel pn_fondo;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JTextArea ta_emisor;
    private javax.swing.JTable tb_factura;
    private RSMaterialComponent.RSTextFieldIconUno txt_direccion;
    private RSMaterialComponent.RSTextFieldIconUno txt_emision;
    private RSMaterialComponent.RSTextFieldIconUno txt_no_fac;
    // End of variables declaration//GEN-END:variables
}
